version: "3.9"

services:
  db:
    image: postgres:15
    container_name: saas_postgres
    restart: always
    environment:
      POSTGRES_DB: saasdb
      POSTGRES_USER: saasuser
      POSTGRES_PASSWORD: saaspass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: saas_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: saasdb
      DB_USER: saasuser
      DB_PASSWORD: saaspass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
