# Generated by Django 6.0.2 on 2026-03-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='auto_create_schema',
        ),
    ]
